config/routes.rb
Rails.application.routes.draw do
  resources :apis

end

app/models/api.rb
class Api < ActiveRecord::Base
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  before_action :set_api, only: [:show, :edit, :update, :destroy]

  # GET /apis
  # GET /apis.json
  def index
    @apis = Api.all
  end

  # GET /apis/1
  # GET /apis/1.json
  def show
     render :json => @api.body
  end

  # GET /apis/new
  def new
    @api = Api.new
  end

  # GET /apis/1/edit
  def edit
  end

  # POST /apis
  # POST /apis.json
  def create
    @api = Api.new(api_params)

    respond_to do |format|
      if @api.save
        format.html { redirect_to @api, notice: 'Api was successfully created.' }
        format.json { render :show, status: :created, location: @api }
      else
        format.html { render :new }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apis/1
  # PATCH/PUT /apis/1.json
  def update
    respond_to do |format|
      if @api.update(api_params)
        format.html { redirect_to @api, notice: 'Api was successfully updated.' }
        format.json { render :show, status: :ok, location: @api }
      else
        format.html { render :edit }
        format.json { render json: @api.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1
  # DELETE /apis/1.json
  def destroy
    @api.destroy
    respond_to do |format|
      format.html { redirect_to apis_url, notice: 'Api was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_api
      @api = Api.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def api_params
      params.require(:api).permit(:name, :body, :memo, :page_type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/apis/_form.html.erb
<%= form_for(@api) do |f| %>
  <% if @api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% @api.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :page_type %><br>
    <%= f.number_field :page_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apis/edit.html.erb
<h1>Editing Api</h1>

<%= render 'form' %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/apis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Apis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Memo</th>
      <th>Page type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apis.each do |api| %>
      <tr>
        <td><%= api.name %></td>
        <td><%= api.body %></td>
        <td><%= api.memo %></td>
        <td><%= api.page_type %></td>
        <td><%= link_to 'Show', api %></td>
        <td><%= link_to 'Edit', edit_api_path(api) %></td>
        <td><%= link_to 'Destroy', api, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api', new_api_path %>

app/views/apis/new.html.erb
<h1>New Api</h1>

<%= render 'form' %>

<%= link_to 'Back', apis_path %>

app/views/apis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @api.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @api.body %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @api.memo %>
</p>

<p>
  <strong>Page type:</strong>
  <%= @api.page_type %>
</p>

<%= link_to 'Edit', edit_api_path(@api) %> |
<%= link_to 'Back', apis_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>